version: "3"

services:
  mongo:
    image: mongo
    restart: always
    container_name: minutes-mongo
    ports:
      - 27017:27017
    volumes:
      - minutes-vol:/data/db

  minutes_app:
    build: .
    ports:
      - 8081:8080
    depends_on:
      - mongo
volumes:
  minutes-vol:
    external: true